site_name: My Docs
site_url: https://docs.kcp.io/kcp/

docs_dir: '../../content/en'
site_dir: '../../generated/branch/en'

theme:
  name: material
  language: en

extra:
  version:
    provider: mike
  alternate:
  - name: English
    link: en
    lang: en

watch:
- mkdocs.yml
- ../../content/en

plugins:
- info
